<?php
    header('Content-Type: application/json');
    error_reporting(E_ALL);
    ini_set('display_errors', 1);

    $response = [];

    if ($_FILES['datafile']['error'] == UPLOAD_ERR_OK) {
        $uploadPath = 'tmp/upload/dates.csv';
        move_uploaded_file($_FILES['datafile']['tmp_name'], $uploadPath);

        // Define the output file path
        $resultFile = 'tmp/output/output.csv';

        // Run the python script
        $output = shell_exec("python scripts/time_calc_v5.py 2>&1");

        // Display or process the output file generated by Python
        if (!file_exists($resultFile)) {
            $response['error'] = "No output generated. Python script output: " . $output;
        } else {
            // Get the Python output and set download link
            $response['output'] = nl2br(htmlspecialchars(file_get_contents($resultFile)));
            $response['downloadLink'] = 'tmp/output/output.csv'; // Ensure this path is correct
        }
    } else {
        $response['error'] = "Error uploading file.";
    }

    echo json_encode($response);
?>
